### ISSUE TITLE
Facebook Comment doesn't dark theme

### ISSUE THREAD

**Issue by mildronize** [dotnetthailand/dotnetthailand.github.io#122]
# Problem
- Unreadable text on dark theme

![image](https://user-images.githubusercontent.com/3647850/129769513-c9d5aa0f-d88e-4184-b25a-64d6937c54d5.png)

**Comment by aaronamm** [comment]
@mildronize  
Thanks for reporting.

**Comment by iamgique** [comment]
I've just done it 
please review and merge.
https://github.com/dotnetthailand/dotnetthailand.github.io/pull/169

I did too much ways to fix it. since theme schema of FB comment till learn about `const theme = useTheme();` send param for switch BG to "commentPlaceHolderStyle" but it not cool when I switch light mode lol.

**Comment by mildronize** [comment]
@iamgique Thank you so much, your contribution is helpful.
