### ISSUE TITLE
Cannot read article and navigate menu at the same time easily

### ISSUE THREAD

**Issue by surrealist** [dotnetthailand/dotnetthailand.github.io#18]
## Problem
We have long list of topics on the left-side menu. When we scroll up and scroll down to navigate topics, it moves the whole page out of sight too. So, user cannot easily continue his or her reading and navigating menu at the same time.

![image](https://user-images.githubusercontent.com/344784/113416161-ee070580-93ea-11eb-8252-bad55339960a.png)

## Proposed solution:
Make left-side menu and content area scrollable independently and fix top navbar at the top.

## Notes
Existing feature: When we click on a topic, it automatically scroll up to the top to help user read the article.

**Comment by aaronamm** [comment]
@surrealist Thanks for open an issue.
BTW, does this website https://www.saladpuk.com/beginner-1/oop match what you expect for in term of scrollable area independently.

But for top menu, I am not sure we need to fix it because we don't have much information that we need to go back and forth. 
![image](https://user-images.githubusercontent.com/2938310/113424121-cd927780-93f9-11eb-9781-b6be7825f79b.png)


We can start by supporting scroll list of topics and main content independently first.

Would you like to make a PR this @surrealist?
It will be an honor to have your profile in this page https://www.dotnetthailand.com/credit. 

You can start by  following an instruction in this document. https://github.com/dotnetthailand/dotnetthailand.github.io#how-to-contribute-to-this-project

Thanks.

**Comment by surrealist** [comment]
Yes, saladpuk.com is a good example solution of this issue. I agree that fixed top navbar is not actually needed as you said. 

BTW, I have no intention to do PR on this issue just want to point out, create an issue, and let people grab to do PR.
